name: 'dbt_project'
version: '1.0'
config-version: 2

profile: 'default'  # nome do perfil no profiles.yml

model-paths: ["models"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
